### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by ntzes** [cwalk/Pi-Temp#4]
Mr. Walker I like your project! 
You have done an excellent work, but I am trying to make it run and I am having these errors.
I am new in this, I would appreciate any help!
Thank you

```
Traceback (most recent call last):
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/bin/flask", line 11, in <module>
    sys.exit(main())
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 906, in main
    cli.main(args=args, prog_name=name)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 569, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 779, in run_command
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 300, in __init__
    self._load_unlocked()
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 324, in _load_unlocked
    self._app = rv = self.loader()
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 381, in load_app
    app = locate_app(self, import_name, name)
  File "/home/pi/Workspace/Pi-Temp/lab_app/env/lib/python3.5/site-packages/flask/cli.py", line 236, in locate_app
    __import__(module_name)
  File "/home/pi/Workspace/Pi-Temp/lab_app/lab_app.py", line 85
    print "rendering lab_env_db.html with: %s, %s, %s" % (timezone, from_date_str, to_date_str)
                                                     ^
SyntaxError: invalid syntax

```

**Comment by Husseo19** [comment]
What python version are you using?

**Comment by cwalk** [comment]
It might be a difference in python versions.
